name: Build and Publish Course

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Build the course files
        run: python scripts/publish.py

      - name: Concatenate markdown files for PDF
        run: python scripts/course_concat.py

      - name: Fix image paths in concatenated markdown
        run: |
          sed -i 's|\.\./\.\./assets/images/|assets/images/|g' course/Redstone-University.md

      - name: Extract solutions for PDF and build appendix
        run: python scripts/extract_solutions.py

      - name: Extract key terms for appendix
        run: python scripts/extract_key_terms.py

      - name: Combine appendices for PDF
        run: python scripts/combine_for_pdf.py

      - name: Generate PDF from processed markdown
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: course/Redstone-University.md
          output_dir: course/
          output_file: Redstone-University.pdf
          build_html: false
          theme: assets/css/pdf-style.css
          pandoc_args: --highlight-style=espresso

      - name: Clean up intermediate files
        run: |
          rm -f course/Redstone-University-for-pdf.md
          rm -f course/Redstone-University-with-key-terms.md

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add course/Redstone-University.pdf appendices/
          if ! git diff --staged --quiet; then
            git commit -m "docs: Rebuild course PDF and appendices"
            git push
          else
            echo "No changes to commit."
          fi
